config/routes.rb
Rails.application.routes.draw do
	resources :books do
		resources :reviews
	end
	resources :accounts

	get 'sessions/index'
	get 'sessions/new'
	post 'sessions/create'
	get 'sessions/destroy'

	root 'books#index'
end

app/models/account.rb
class Account < ActiveRecord::Base
	validates_presence_of :name, :username, :password
	has_secure_password

	has_many :book
	has_many :review
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :account
	belongs_to :category
	has_many :review

	validates_presence_of :title, :description, :author 

	mount_uploader :book_img, BookImgUploader	
	#validates_integrity_of :book_img


end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :book
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :book
	belongs_to :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def index
		@accounts = Account.all
	end

	def new
		@account = Account.new
	end

	def create
		@account = Account.new(account_params)

		if @account.save
			redirect_to accounts_path, notice: 'Successful Sign Up!'
		else 
			render 'new'
		end
	end

	private 
		def account_params
			params.require(:account).permit(:name, :username, :password)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private

  def current_user
  	User.where(id:session[:user_id]).first
  end
  
  helper_method :current_user

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user, only: [:new, :update, :edit]

	def index
		if params[:category].blank?
			@books = Book.all
			@categories = Category.all
		else
			@books = Book.where(category_id: params[:category])
			@book_category = Category.find(params[:category]).category
			@categories = Category.all
		end
	end

	def show
		@average = @book.review.average(:rating)
		@no_of_review = @book.review.count
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = session[:account_id]
		if session[:account_id] == nil
			redirect_to sessions_new_path, notice: 'You must be logged in to Add A New Book!'
		else
			if @book.save
				redirect_to root_path, notice: 'Book Added!'
			else
				render 'new'
			end
		end
	end

	def edit
	end

	def update
		if @book.update(book_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@book.destroy
		redirect_to books_path
	end

	def add_review
		render 'form'
	end

	private
		def book_params
			params.require(:book).permit(
				:title, :description, :author, :category_id,
				:user_id, :book_img)
		end

		def find_book
			@book = Book.find(params[:id])
		end

		def authenticate_user
			if session[:account_id] == nil
				redirect_to sessions_new_path, notice: 'You must be logged in.'
			end
		end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :find_book
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user, only: [:new, :create]

	def index
		@book = @book_id
	end

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.user_id = session[:account_id]

		if @review.save
			redirect_to book_path(@book)
		else
			render 'new'
		end
		#@review.user_id = 
	end

	def edit
	end

	def update

		if @review.update(review_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to book_path(@book)
	end

	private
		def review_params
			params.require(:review).permit(:rating, :comment, :book_id)
		end

		def find_book
			@book = Book.find(params[:book_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

		def authenticate_user
			if session[:account_id] == nil
				redirect_to sessions_new_path, notice: 'You must be logged in to Post Review'
			end
		end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@session = Account.new
	end

	def create
		#@session = Account.new(session_params)
		username = Account.where(username: params[:username]).first
		#if username && username.authenticate(params[:password])
		if username && username.authenticate(params[:password_digest])
			redirect_to books_path, notice: 'Logged IN'
			session[:isLogged] = 'logged'
			session[:account_id] = username.id
		else
			redirect_to sessions_new_path, notice: 'Invalid Username/Password'
		end


	end

	def destroy
		session[:isLogged] = nil
		session[:account_id] = nil
		redirect_to sessions_new_path, notice: 'Logged Out!'
	end

	# private
	# 	def session_params
	# 		params.require(:account).permit(:username, :password)
	# 	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name , class: 'form-control' %>
</div>
<div class="form-group">
	<%= f.label :username %>
	<%= f.text_field :username , class: 'form-control' %>
</div>
<div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password , class: 'form-control' %>
</div>
<div class="form-group">
	<%= f.submit class: 'btn btn-success btn-block' %>
</div>

<% end %>

app/views/accounts/index.html.erb
<h1>All Accounts</h1>

<%= notice %>

app/views/accounts/new.html.erb
<h1>Sign Up!</h1>

<%= render 'form' %>

app/views/books/_form.html.erb
<%= form_for(@book, html:{ multipart:true })  do |f| %>

<% if @book.errors.any?%>
	<% @book.errors.full_messages.each do |m| %>
	<%= m %>
	<% end %>
<% end %>


<div class="form-group">
	<%= f.label 'Book Category' %>
	<%= f.select(:category_id, options_for_select(Category.all.map{ |c| [c.category, c.id]})) %>
</div>
<div class="form-group">
	<%= f.label :title %>
	<%= f.text_field :title , class: 'form-control' %>
</div>
<div class="form-group">
	<%= f.label :description %>
	<%= f.text_area :description , class: 'form-control', rows: 8 %>
</div>
<div class="from-group">
	<%= f.label :author %>
	<%= f.text_field :author , class: 'form-control' %>
</div>
<div class="from-group">
	<%= f.label :book_img %>
	<%= f.file_field :book_img , class: 'form-control' %>
</div>
<br>
<div class="form-group">
	<%= f.submit %>
</div>

<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<% if notice %>
<div class="alert alert-success" role="alert" style="padding:1%">
	<%=notice %>
</div>
<% end %>

<% if @books.count ===0 %>
<h1><%= @book_category %></h1>
	<% if books_path %>
	<div class="alert alert-warning" role="alert" style="padding:1%">
		No Book under <%= @book_category %>
	</div>
	<% end %>
<% else %>
	<% if params[:category].blank? %>
<% end %>

<h1><%= @book_category %></h1>
	<% @books.each do |book| %>
		<div class="col-md-3">
		<br>
			<center>
				<%= link_to (image_tag(book.book_img, class: 'img img-round thumbnail', height: '250', width:'200')) , book_path(book.id) %>
			</center>
		</div>
		
	<% end %>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<br>
<div class="row">
	<div class="well col-md-3">
		<img src="<%= @book.book_img%>" heigt="250" width="100%">
	</div>
	<div class="well col-md-8 col-md-offset-1">
		<h3><%= @book.title %> 
		<small>
			<% if @book.user_id == session[:account_id] %>
				 - <%= link_to 'Edit' , edit_book_path(@book) %> | <%= link_to 'Delete', book_path(@book) ,method: :delete, data: {confirm: 'Are you sure?'} %>
			<% end %>
		</small>
		</h3>
		<h4>from <%= @book.author %></h4>

		<!-- Check # of reviews -->
		<% if @no_of_review < 1 %>
		    <p>The Book hasn't reviewed.</p>
		<% else %>
		    <div class="average-rating" data-score="<%= @average %>"><h5>Average Rating</h5></div>
			<i>Based on <%= @no_of_review %> review(s)</i>
		<% end %>
		<p><%= @book.description %></p>
		<hr>
		<br>
	</div>
</div>
<div class="row col-md-4 well">
	<h4>Reviews</h4>
	<%= link_to 'Add Review', new_book_review_path(@book), class:'btn btn-default' %> <br>
	<!-- render reviews here -->

	<br><%= render @book.review %>

	<%= link_to 'Back', root_path , class:'btn btn-default' %>

</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-rating').raty({
		readOnly: true,
		score: function(){
			return $(this).attr('data-score')
		},
		path: '/assets/'
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book Review</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <style type="text/css">
     a{text-decoration:none;}
  </style>
</head>
<body class="yellow lighten-5">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Book Review</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
        <% if session[:account_id] == nil %>
         <%= link_to 'SIGN UP', new_account_path %>
        <% end %>
       
        <!-- <a href="#">Sign Up <span class="sr-only">(current)</span></a> --></li>
        <% if session[:isLogged] == 'logged' %>
          <li><%= link_to 'LOG OUT', sessions_destroy_path %></li>
        <% else %>
          <li><%= link_to 'LOG IN', sessions_new_path %></li>
        <% end %>

      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CATEGORIES <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <% Category.all.each do |c| %>
            <li>
              <%= link_to c.category, books_path(category: c.id)%>
            </li>
          <% end %>
          </ul>
        </li>
        <% if session[:account_id] != nil %>
          <li><a href="/books/new">Add Book</a></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
	<%= yield %>
</div>


    
</body>
</html>

app/views/reviews/_form.html.erb
<div class="col-md-8">
	<%= form_for([@book, @book.review.build]) do |f|  %>
	<div class="form-group">
		<%= f.label :rating %>
		<div id="rating-form">
			
		</div>
		
	</div>
	<div class="form-group">


	</div>
	<div class="form-group">
		<%= f.label :comment  %>
		<%= f.text_area :comment, class:'form-control', rows:'8' %>
	</div>

	<%= f.text_field :book_id , type:'hidden'%>
	<%= f.text_field :user_id, :value => session[:account_id], type:'hidden'%>
	<br>
	<%= f.submit class:'btn btn-success' %>
	<% end %>	
</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>">	
</div>
<b><%= Account.find(review.user_id).name %></b>

<% if review.user_id == session[:account_id] %>
	<%= link_to 'Edit', edit_book_review_path(review.book, review) %> |
	<%= link_to 'Delete', book_review_path(review.book, review) , method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>

<p><%= review.comment %></p>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function(){
			$(this).attr('data-score')
		},
		path: '/assets/'
	});
</script>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= form_for([@book, @review]) do |f|%>
<div class="col-md-8">
	<form>
		<div class="form-group">
			<%= f.label 'Rating' %>
			<div class="rating"></div>
		</div>
		<div class="form-group">
			<%= f.label 'Comment' %>
			<%= f.text_area :comment, class: 'form-control'%>
		</div>
		<div class="form-group">
			<%= f.submit  %>
		</div>
	</form>
</div>

<% end %>

<script>
	$('.rating').raty({
		scoreName: 'review[rating]',
		path: '/assets/'
	});

</script>

app/views/reviews/index.html.erb
<h1>Index</h1>

<%= @book %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>